# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOTNET_VERSION: 8.0.x

jobs:
  build-native:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore src/apps/AOC2023.Cli
    - name: Build CLI
      run: dotnet publish src/apps/AOC2023.Cli --no-restore -c Release -o deploy --nologo
    - name: Pack TAR with build
      run: tar -czvf linux-build.tar.gz -C deploy .
    - uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: linux-build.tar.gz

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore tests/AOC2023.Tests
    - name: Build Debug
      run: dotnet build tests/AOC2023.Tests --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  native-single:
    runs-on: ubuntu-latest
    needs: build-native
    strategy:
      matrix:
        day: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: linux-build
        path: .
    - name: Extract build
      run: mkdir runtime && tar -xzvf linux-build.tar.gz -C runtime
    - name: Execute
      working-directory: runtime
      run: ./aoc2023 ${{ matrix.day }}