# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Debug
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build Release
      run: dotnet build --no-restore -c Release
    - name: Pack TAR with build
      run: tar -czvf linux-build.tar.gz AOC2023/bin/Release/net8.0
    - uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: linux-build.tar.gz

  execute-days:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        day: [1, 2]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - uses: actions/download-artifact@v3
      with:
        name: linux-build
        path: linux-build.tar.gz
    - name: Extract build
      run: tar -xzvf linux-build.tar.gz -C runtime
    - name: List artifact content
      run: ls -Rlah runtime
    - name: Execute
      working-directory: runtime
      run: ./AOC2023 ${{ matrix.day }}