# Deploy to GitHub Pages using WebAssembly
name: Deploy to GitHub Pages

on:
    push:
      branches: [ "main" ]
    workflow_dispatch:

env:
    DOTNET_VERSION: 8.0.x

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Setup Pages
          uses: actions/configure-pages@v3
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
        - name: Setup additional workloads
          run: dotnet workload install wasm-tools
        - name: Restore dependencies
          run: dotnet restore
        - name: Build 
          run: dotnet publish AOC2023.WebApp --no-restore -c Release -o deploy --nologo 
        - name: Upload web application
          uses: actions/upload-pages-artifact@v2
          with:
            path: "deploy/wwwroot" 
    
    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment: 
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2
        